In [97]:
import pandas as pd

`clean-weather.csv` contains the weather/wildfire data after having being thoroughly processed and cleaned in `data-cleaning-preparation.ipnyb`.

In [98]:
df = pd.read_csv('clean-weather-2.csv')

In [99]:
df.head()

,LATITUDE,LONGITUDE,ELEVATION,STATION_NAME,PROVINCE_CODE,ID,LOCAL_DATE,LOCAL_DAY,LOCAL_MONTH,LOCAL_YEAR,...,MAX_TEMPERATURE,MEAN_TEMPERATURE,SNOW_ON_GROUND,TOTAL_SNOW,TOTAL_PRECIPITATION,TOTAL_RAIN,MIN_REL_HUMIDITY,MAX_REL_HUMIDITY,SPEED_MAX_GUST,hectares
0,52.1276,-124.0569,1371.6,PUNTZI MOUNTAIN (AUT),BC,1086558.2000.4.12,2000-04-12 00:00:00,12.0,4.0,2000.0,...,16.9,6.3,0.0,0.0,0.0,0.0,21.0,95.0,33.0,7.1
1,52.3217,-124.3200,1371.6,PUNTZI MOUNTAIN (AUT),BC,1086558.2000.4.27,2000-04-27 00:00:00,27.0,4.0,2000.0,...,16.7,9.6,0.0,0.0,0.0,0.0,36.0,67.0,50.0,1.0
2,52.2062,-124.3317,1371.6,PUNTZI MOUNTAIN (AUT),BC,1086558.2000.4.28,2000-04-28 00:00:00,28.0,4.0,2000.0,...,11.9,4.4,0.0,0.0,0.0,0.0,26.0,88.0,46.0,0.2
3,52.1116,-124.0862,1371.6,PUNTZI MOUNTAIN (AUT),BC,1086558.2000.4.30,2000-04-30 00:00:00,30.0,4.0,2000.0,...,12.8,7.0,0.0,0.0,0.0,0.0,32.0,73.0,44.0,0.3
4,52.1227,-124.0877,1371.6,PUNTZI MOUNTAIN (AUT),BC,1086558.2001.3.25,2001-03-25 00:00:00,25.0,3.0,2001.0,...,13.0,4.6,0.0,0.0,0.0,0.0,30.0,89.0,52.0,2.5

In [100]:
df.describe()

,LATITUDE,LONGITUDE,ELEVATION,LOCAL_DAY,LOCAL_MONTH,LOCAL_YEAR,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,SNOW_ON_GROUND,TOTAL_SNOW,TOTAL_PRECIPITATION,TOTAL_RAIN,MIN_REL_HUMIDITY,MAX_REL_HUMIDITY,SPEED_MAX_GUST,hectares
count,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000,11246.000000
mean,52.215455,-96.030151,373.531309,15.572381,5.705317,2012.169838,4.261007,17.508464,10.899443,2.467455,0.036395,1.476507,0.296399,41.941757,87.584386,29.686555,404.034033
std,4.831971,20.421664,275.495649,8.819481,1.814360,6.731882,9.441052,10.442319,9.641380,10.237672,0.614982,4.629405,2.181321,17.475025,11.552295,21.848576,7462.498281
min,41.261400,-157.247000,2.000000,1.000000,1.000000,2000.000000,-44.000000,-41.300000,-42.700000,0.000000,0.000000,0.000000,0.000000,8.000000,22.000000,0.000000,0.000000
25%,49.108108,-114.845675,213.100000,8.000000,4.000000,2008.000000,-1.400000,10.800000,5.000000,0.000000,0.000000,0.000000,0.000000,29.000000,82.000000,0.000000,0.000000
50%,51.265700,-93.473500,341.700000,16.000000,6.000000,2011.000000,5.900000,19.800000,13.100000,0.000000,0.000000,0.000000,0.000000,39.000000,91.000000,35.000000,0.009000
75%,54.995125,-80.234000,457.200000,23.000000,7.000000,2019.000000,11.300000,25.400000,18.100000,0.000000,0.000000,0.500000,0.000000,53.000000,96.000000,44.000000,0.400000
max,82.310400,116.128900,2543.000000,31.000000,12.000000,2024.000000,25.400000,42.200000,30.600000,140.000000,32.800000,89.000000,59.000000,100.000000,100.000000,149.000000,541766.000000

# Modeling
It is not evident which model would best be used for our dataset, so we perform simple tests to see if basic models might be viable using a single test-train split

In [101]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error

In [102]:
# x = df[['LATITUDE', 'LONGITUDE', 'MIN_TEMPERATURE', 'MAX_TEMPERATURE', 'MIN_TEMPERATURE', 'SNOW_ON_GROUND', 'TOTAL_SNOW', 'TOTAL_PRECIPITATION', 'TOTAL_RAIN', 'MIN_REL_HUMIDITY', 'MAX_REL_HUMIDITY', 'SPEED_MAX_GUST']] # Only select weather data
x = df[['LATITUDE', 'LONGITUDE','MIN_TEMPERATURE', 'MAX_TEMPERATURE', 'MIN_TEMPERATURE', 'SNOW_ON_GROUND', 'TOTAL_SNOW', 'TOTAL_PRECIPITATION', 'TOTAL_RAIN']] # Only select weather data
y = df['hectares']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Linear Regression model

In [103]:
from sklearn.linear_model import LinearRegression

In [104]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [105]:
# Predicting on the train set
y_pred = model.predict(x_test)

In [106]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 739.5888411758395
MSE: 23130531.806201246
RMSE: 4809.421150845624
R²: 0.004293996023417512

In [107]:
y_train_pred = model.predict(x_train)

In [108]:
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 897.4583544941644
MSE: 63485737.749229476
RMSE: 7967.793781796155
R²: 0.004858147500310439

## Decision Tree Regressor

In [109]:
from sklearn.tree import DecisionTreeRegressor

In [110]:
model = DecisionTreeRegressor()
model.fit(x_train, y_train)

DecisionTreeRegressor()

In [111]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 441.00458981785016
MSE: 27055501.157400697
RMSE: 5201.490282351847
R²: -0.16466517798768776

In [112]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 0.0004647621349045701
MSE: 0.00020615723654957764
RMSE: 0.014358176644322831
R²: 0.9999999999967685

Decision Tree Regressor has overfit

## Random Forests Regressor

In [113]:
from sklearn.ensemble import RandomForestRegressor

In [114]:
model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [115]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 636.3766850127568
MSE: 31526226.543891765
RMSE: 5614.8220402691095
R²: -0.3571176536487204

In [116]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 287.54757852223895
MSE: 7766584.271695303
RMSE: 2786.8592127510324
R²: 0.8782584351424093

## Gradient Boosting Model

In [117]:
from sklearn.ensemble import GradientBoostingRegressor

In [118]:
model = GradientBoostingRegressor()
model.fit(x_train, y_train)

GradientBoostingRegressor()

In [119]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 610.8954860002677
MSE: 24496084.49713347
RMSE: 4949.351926983317
R²: -0.0544893049616062

In [120]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 578.0313261456919
MSE: 12751196.866945613
RMSE: 3570.8818052332135
R²: 0.800124403974269

## K-Nearest Neighbors

In [121]:
from sklearn.neighbors import KNeighborsRegressor

In [122]:
model = KNeighborsRegressor()
model.fit(x_train, y_train)

KNeighborsRegressor()

In [123]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 642.0922685836244
MSE: 34921845.921087585
RMSE: 5909.470866421763
R²: -0.5032897619867851

In [124]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 629.599598825191
MSE: 43880198.431945615
RMSE: 6624.213042463657
R²: 0.3121758759722326

## Support Vector Machines

In [125]:
from sklearn.svm import SVR

In [126]:
model = SVR()
model.fit(x_train, y_train)

SVR()

In [127]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 274.07134940797073
MSE: 23305257.923585806
RMSE: 4827.551959698187
R²: -0.0032274844850712636

In [128]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 436.53831582424095
MSE: 63986025.64360533
RMSE: 7999.126555043702
R²: -0.002983888201612217