In [1]:
import pandas as pd

`clean-weather.csv` contains the weather/wildfire data after having being thoroughly processed and cleaned in `data-cleaning-preparation.ipnyb`.

In [2]:
df = pd.read_csv('clean-weather.csv')

In [3]:
df.head()

,LATITUDE,LONGITUDE,ELEVATION,STATION_NAME,PROVINCE_CODE,ID,LOCAL_DATE,LOCAL_DAY,LOCAL_MONTH,LOCAL_YEAR,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,SNOW_ON_GROUND,TOTAL_SNOW,TOTAL_PRECIPITATION,TOTAL_RAIN,hectares
0,50.9050,-126.9292,14.0,EGG ISLAND,BC,1062646.2000.3.10,2000-03-10 00:00:00,10.0,3.0,2000.0,2.0,11.3,6.7,0.0,0.0,3.5,3.5,6.0
1,59.9617,-121.3608,498.0,SAMBAA K'E,NT,220CQHR.2000.6.27,2000-06-27 00:00:00,27.0,6.0,2000.0,7.9,27.0,17.5,0.0,0.0,0.0,0.0,1000.0
2,59.9752,-121.0342,498.0,SAMBAA K'E,NT,220CQHR.2000.7.11,2000-07-11 00:00:00,11.0,7.0,2000.0,9.9,20.9,15.4,0.0,0.0,0.0,0.0,12.0
3,59.1767,-122.0190,378.3,FORT NELSON UA,BC,1192950.2001.6.13,2001-06-13 00:00:00,13.0,6.0,2001.0,8.5,26.8,17.7,0.0,0.0,0.0,0.0,5.0
4,59.4008,-120.6438,777.2,PETITOT LO,AB,3075171.2000.6.26,2000-06-26 00:00:00,26.0,6.0,2000.0,8.0,24.0,16.0,0.0,0.0,1.2,1.2,0.1

In [4]:
df.describe()

,LATITUDE,LONGITUDE,ELEVATION,LOCAL_DAY,LOCAL_MONTH,LOCAL_YEAR,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,SNOW_ON_GROUND,TOTAL_SNOW,TOTAL_PRECIPITATION,TOTAL_RAIN,hectares
count,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000,57666.000000
mean,52.443934,-102.165135,502.642020,15.491624,5.842368,2009.088787,4.925190,18.486696,11.721789,2.615430,0.101623,1.678459,1.135021,257.431717
std,4.707561,20.771427,392.902579,8.822762,1.728554,6.648006,8.582523,9.605800,8.742616,11.997669,1.026405,4.787095,4.034979,5361.099326
min,40.065300,-162.480000,1.200000,1.000000,1.000000,1999.000000,-46.900000,-42.700000,-44.800000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,49.210100,-117.763088,224.100000,8.000000,5.000000,2004.000000,0.000000,13.000000,6.900000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,52.031100,-111.272683,419.000000,15.000000,6.000000,2008.000000,6.400000,20.500000,13.500000,0.000000,0.000000,0.000000,0.000000,0.009000
75%,55.500000,-84.569900,690.400000,23.000000,7.000000,2014.000000,11.000000,25.500000,18.000000,0.000000,0.000000,0.900000,0.000000,0.200000
max,82.310400,116.188000,2926.100000,31.000000,12.000000,2024.000000,26.500000,47.900000,34.400000,319.000000,37.000000,168.000000,168.000000,577646.800000

# Modeling
It is not evident which model would best be used for our dataset, so we perform simple tests to see if basic models might be viable using a single test-train split

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error

In [6]:
x = df[['LATITUDE', 'LONGITUDE', 'ELEVATION', 'MIN_TEMPERATURE', 'MAX_TEMPERATURE', 'MIN_TEMPERATURE', 'SNOW_ON_GROUND', 'TOTAL_SNOW', 'TOTAL_PRECIPITATION', 'TOTAL_RAIN']] # Only select weather data
y = df['hectares']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Linear Regression model

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [9]:
# Predicting on the train set
y_pred = model.predict(x_test)

In [10]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 552.6832779765689
MSE: 10649305.458037872
RMSE: 3263.3273599254294
R²: 0.008303445012858512

In [11]:
y_train_pred = model.predict(x_train)

In [12]:
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 599.3314239895781
MSE: 33060789.50097314
RMSE: 5749.851259030371
R²: 0.005430422753051722

## Decision Tree Regressor

In [13]:
from sklearn.tree import DecisionTreeRegressor

In [14]:
model = DecisionTreeRegressor()
model.fit(x_train, y_train)

DecisionTreeRegressor()

In [15]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 496.37853252604106
MSE: 55146930.881464206
RMSE: 7426.097957976598
R²: -4.135454287489137

In [16]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 0.10758759647678486
MSE: 86.38813861615586
RMSE: 9.294521968135632
R²: 0.9999974011808006

Decision Tree Regressor has overfit

## Random Forests Regressor

In [17]:
from sklearn.ensemble import RandomForestRegressor

In [18]:
model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [19]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 474.78920392766827
MSE: 20886789.854341257
RMSE: 4570.206762756064
R²: -0.9450430476343032

In [20]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 176.78473978391227
MSE: 4104902.3086409434
RMSE: 2026.0558503261807
R²: 0.876511994560055

## Gradient Boosting Model

In [21]:
from sklearn.ensemble import GradientBoostingRegressor

In [22]:
model = GradientBoostingRegressor()
model.fit(x_train, y_train)

GradientBoostingRegressor()

In [23]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 472.7733978448896
MSE: 17104421.22846874
RMSE: 4135.749173785656
R²: -0.5928170784620062

In [24]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 440.5860294409245
MSE: 15926012.956596145
RMSE: 3990.7409032153596
R²: 0.5208968626413166

## K-Nearest Neighbors

In [25]:
from sklearn.neighbors import KNeighborsRegressor

In [26]:
model = KNeighborsRegressor()
model.fit(x_train, y_train)

KNeighborsRegressor()

In [27]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 477.4895145902978
MSE: 24974463.65501869
RMSE: 4997.445713063694
R²: -1.3256999873771047

In [28]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 389.7444085221679
MSE: 25670327.79751323
RMSE: 5066.589365392979
R²: 0.22775809499008426

## Support Vector Machines

In [29]:
from sklearn.svm import SVR

In [30]:
model = SVR()
model.fit(x_train, y_train)

SVR()

In [31]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 214.44223979699885
MSE: 10784377.305412866
RMSE: 3283.9575675414667
R²: -0.004274866901035068

In [32]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 268.1950118072507
MSE: 33313136.30977807
RMSE: 5771.753313316333
R²: -0.0021609403916593717