In [236]:
import pandas as pd

`clean-weather.csv` contains the weather/wildfire data after having being thoroughly processed and cleaned in `data-cleaning-preparation.ipnyb`.

In [237]:
df = pd.read_csv('clean-weather-3.csv')

In [238]:
df.head()

,LATITUDE,LONGITUDE,ELEVATION,STATION_NAME,PROVINCE_CODE,ID,LOCAL_DATE,LOCAL_DAY,LOCAL_MONTH,LOCAL_YEAR,...,MAX_TEMPERATURE,MEAN_TEMPERATURE,SNOW_ON_GROUND,TOTAL_SNOW,TOTAL_RAIN,TOTAL_PRECIPITATION,MIN_REL_HUMIDITY,MAX_REL_HUMIDITY,SPEED_MAX_GUST,hectares
0,50.9050,-126.9292,14.0,EGG ISLAND,BC,1062646.2000.3.10,2000-03-10 00:00:00,10.0,3.0,2000.0,...,11.3,6.7,0.0,0.0,3.5,3.5,NaN,NaN,NaN,6.0
1,59.9617,-121.3608,498.0,SAMBAA K'E,NT,220CQHR.2000.6.27,2000-06-27 00:00:00,27.0,6.0,2000.0,...,27.0,17.5,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1000.0
2,59.9752,-121.0342,498.0,SAMBAA K'E,NT,220CQHR.2000.7.11,2000-07-11 00:00:00,11.0,7.0,2000.0,...,20.9,15.4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,12.0
3,59.1767,-122.0190,378.3,FORT NELSON UA,BC,1192950.2001.6.13,2001-06-13 00:00:00,13.0,6.0,2001.0,...,26.8,17.7,0.0,0.0,0.0,0.0,NaN,NaN,NaN,5.0
4,59.4008,-120.6438,777.2,PETITOT LO,AB,3075171.2000.6.26,2000-06-26 00:00:00,26.0,6.0,2000.0,...,24.0,16.0,0.0,0.0,1.2,1.2,NaN,NaN,NaN,0.1

In [239]:
df.describe()

,LATITUDE,LONGITUDE,ELEVATION,LOCAL_DAY,LOCAL_MONTH,LOCAL_YEAR,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,SNOW_ON_GROUND,TOTAL_SNOW,TOTAL_RAIN,TOTAL_PRECIPITATION,MIN_REL_HUMIDITY,MAX_REL_HUMIDITY,SPEED_MAX_GUST,hectares
count,59732.000000,59732.000000,59572.000000,59732.00000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,14295.00000,14302.000000,19311.000000,59732.000000
mean,52.430932,-101.861180,498.738882,15.50437,5.835147,2009.038204,4.713177,18.190861,11.467476,2.705826,0.106384,1.125370,1.673659,41.89213,87.851559,26.892341,248.934998
std,4.680110,20.590721,389.618273,8.80355,1.794696,6.677045,8.798398,9.858715,8.986341,12.224479,1.051774,4.046445,4.796884,17.45177,11.283643,22.494157,5267.998994
min,40.065300,-162.480000,1.200000,1.00000,1.000000,1999.000000,-46.900000,-42.700000,-44.800000,0.000000,0.000000,0.000000,0.000000,8.00000,22.000000,0.000000,0.000000
25%,49.230000,-117.542833,226.125000,8.00000,5.000000,2003.000000,-0.100000,12.600000,6.500000,0.000000,0.000000,0.000000,0.000000,29.00000,82.250000,0.000000,0.000000
50%,51.958800,-110.581933,390.800000,15.00000,6.000000,2007.000000,6.100000,20.000000,13.400000,0.000000,0.000000,0.000000,0.000000,39.00000,91.000000,33.000000,0.009000
75%,55.411950,-85.678991,683.300000,23.00000,7.000000,2014.000000,11.000000,25.400000,18.000000,0.000000,0.000000,0.000000,0.900000,52.00000,96.000000,43.000000,0.200000
max,82.310400,116.188000,2926.100000,31.00000,12.000000,2024.000000,26.500000,47.900000,34.400000,322.000000,38.600000,168.000000,168.000000,100.00000,100.000000,149.000000,577646.800000

# Classification
We turn this into a classification problem by creating a class column, where 0 means no fire and 1 means fire

In [240]:
df['CLASS'] = (df.loc[:, 'hectares'] > 0).astype(int)

# Modeling
It is not evident which model would best be used for our dataset, so we perform simple tests to see if basic models might be viable using a single test-train split

In [241]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [242]:
# x = df[['LATITUDE', 'LONGITUDE', 'ELEVATION', 'MEAN_TEMPERATURE', 'MAX_TEMPERATURE', 'MIN_TEMPERATURE', 'SNOW_ON_GROUND', 'TOTAL_SNOW', 'TOTAL_PRECIPITATION', 'TOTAL_RAIN' 'MIN_REL_HUMIDITY', 'MAX_REL_HUMIDITY', 'SPEED_MAX_GUST']] # Only select weather data
df.dropna(subset=['ELEVATION'], inplace=True)
x = df[['LATITUDE', 'LONGITUDE', 'ELEVATION', 'MEAN_TEMPERATURE', 'MAX_TEMPERATURE', 'MIN_TEMPERATURE', 'SNOW_ON_GROUND', 'TOTAL_SNOW', 'TOTAL_PRECIPITATION', 'TOTAL_RAIN']] # Only select weather data
y = df['CLASS']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Logistic Regression model

In [243]:
from sklearn.linear_model import LogisticRegression

In [244]:
model = LogisticRegression()
model.fit(x_train, y_train)

C:\Users\ethan\PycharmProjects\fire-guard\model\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [245]:
# Predicting on the train set
y_pred_train = model.predict(x_train)
# Evaluating the model on the train set
accuracy_train = accuracy_score(y_train, y_pred_train)
precision_train = precision_score(y_train, y_pred_train)
recall_train = recall_score(y_train, y_pred_train)
f1_train = f1_score(y_train, y_pred_train)
print(f"Accuracy: {accuracy_train}")
print(f"Precision: {precision_train}")
print(f"Recall: {recall_train}")
print(f"f1: {f1_train}")

Accuracy: 0.6907274901903183
Precision: 0.6704916411118805
Recall: 0.8107655502392345
f1: 0.733986680383345

In [246]:
# Predicting on the test set
y_pred_test = model.predict(x_test)
accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test)
recall_test = recall_score(y_test, y_pred_test)
f1_test = f1_score(y_test, y_pred_test)
print(f"Accuracy: {accuracy_test}")
print(f"Precision: {precision_test}")
print(f"Recall: {recall_test}")
print(f"f1: {f1_test}")

Accuracy: 0.6791439362148552
Precision: 0.6574294008973344
Recall: 0.8023836366564664
f1: 0.7227097990860956

## Decision Tree Classifier

In [247]:
from sklearn.tree import DecisionTreeClassifier

In [248]:
model = DecisionTreeClassifier(random_state=11)
model.fit(x_train, y_train)

DecisionTreeClassifier(random_state=11)

In [249]:
# Predicting on the train set
y_pred_train = model.predict(x_train)

# Evaluating the model on the train set
accuracy_train = accuracy_score(y_train, y_pred_train)
precision_train = precision_score(y_train, y_pred_train)
recall_train = recall_score(y_train, y_pred_train)
f1_train = f1_score(y_train, y_pred_train)

print(f"Accuracy: {accuracy_train}")
print(f"Precision: {precision_train}")
print(f"Recall: {recall_train}")
print(f"f1: {f1_train}")

Accuracy: 0.9999580334473425
Precision: 1.0
Recall: 0.9999202551834131
f1: 0.9999601260018341

In [250]:
# Predicting on the test set
y_pred_test = model.predict(x_test)
accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test)
recall_test = recall_score(y_test, y_pred_test)
f1_test = f1_score(y_test, y_pred_test)
print(f"Accuracy: {accuracy_test}")
print(f"Precision: {precision_test}")
print(f"Recall: {recall_test}")
print(f"f1: {f1_test}")

Accuracy: 0.8375996642887117
Precision: 0.8489549314173742
Recall: 0.8373329038492511
f1: 0.8431038676720992

Decision Tree Regressor has overfit

## Random Forests

In [251]:
from sklearn.ensemble import RandomForestClassifier

In [252]:
model = RandomForestClassifier()
model.fit(x_train, y_train)

RandomForestClassifier()

In [253]:
# Predicting on the train set
y_pred_train = model.predict(x_train)

# Evaluating the model on the train set
accuracy_train = accuracy_score(y_train, y_pred_train)
precision_train = precision_score(y_train, y_pred_train)
recall_train = recall_score(y_train, y_pred_train)
f1_train = f1_score(y_train, y_pred_train)

print(f"Accuracy: {accuracy_train}")
print(f"Precision: {precision_train}")
print(f"Recall: {recall_train}")
print(f"f1: {f1_train}")

Accuracy: 0.9999580334473425
Precision: 0.9999601275917065
Recall: 0.9999601275917065
f1: 0.9999601275917065

In [254]:
# Predicting on the test set
y_pred_test = model.predict(x_test)
accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test)
recall_test = recall_score(y_test, y_pred_test)
f1_test = f1_score(y_test, y_pred_test)
print(f"Accuracy: {accuracy_test}")
print(f"Precision: {precision_test}")
print(f"Recall: {recall_test}")
print(f"f1: {f1_test}")

Accuracy: 0.8395300041963911
Precision: 0.8458071784967005
Recall: 0.8463520695764213
f1: 0.8460795363065529

## Gradient Boosting Model

In [255]:
from sklearn.ensemble import GradientBoostingClassifier

In [256]:
model = GradientBoostingClassifier()
model.fit(x_train, y_train)

GradientBoostingClassifier()

In [257]:
# Predicting on the train set
y_pred_train = model.predict(x_train)

# Evaluating the model on the train set
accuracy_train = accuracy_score(y_train, y_pred_train)
precision_train = precision_score(y_train, y_pred_train)
recall_train = recall_score(y_train, y_pred_train)
f1_train = f1_score(y_train, y_pred_train)

print(f"Accuracy: {accuracy_train}")
print(f"Precision: {precision_train}")
print(f"Recall: {recall_train}")
print(f"f1: {f1_train}")

Accuracy: 0.7783326688629163
Precision: 0.7691138301816833
Recall: 0.82707336523126
f1: 0.7970413064361191

In [258]:
# Predicting on the test set
y_pred_test = model.predict(x_test)
accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test)
recall_test = recall_score(y_test, y_pred_test)
f1_test = f1_score(y_test, y_pred_test)
print(f"Accuracy: {accuracy_test}")
print(f"Precision: {precision_test}")
print(f"Recall: {recall_test}")
print(f"f1: {f1_test}")

Accuracy: 0.7669324381032312
Precision: 0.75696316262354
Recall: 0.8141407634079562
f1: 0.7845115232404749

## K-Nearest Neighbors

In [259]:
from sklearn.neighbors import KNeighborsClassifier

In [260]:
model = KNeighborsClassifier()
model.fit(x_train, y_train)

KNeighborsClassifier()

In [261]:
# Predicting on the train set
y_pred_train = model.predict(x_train)

# Evaluating the model on the train set
accuracy_train = accuracy_score(y_train, y_pred_train)
precision_train = precision_score(y_train, y_pred_train)
recall_train = recall_score(y_train, y_pred_train)
f1_train = f1_score(y_train, y_pred_train)

print(f"Accuracy: {accuracy_train}")
print(f"Precision: {precision_train}")
print(f"Recall: {recall_train}")
print(f"f1: {f1_train}")

Accuracy: 0.8087164529869694
Precision: 0.8012985052091197
Recall: 0.8464114832535885
f1: 0.8232374156519041

In [262]:
# Predicting on the test set
y_pred_test = model.predict(x_test)

accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test)
recall_test = recall_score(y_test, y_pred_test)
f1_test = f1_score(y_test, y_pred_test)
print(f"Accuracy: {accuracy_test}")
print(f"Precision: {precision_test}")
print(f"Recall: {recall_test}")
print(f"f1: {f1_test}")

Accuracy: 0.7184221569450273
Precision: 0.7151040096472716
Recall: 0.7640521823159929
f1: 0.7387682005761894

## Support Vector Machines

In [263]:
from sklearn.svm import SVC

In [264]:
model = SVC()
model.fit(x_train, y_train)

SVC()

In [265]:
# Predicting on the train set
y_pred_train = model.predict(x_train)

# Evaluating the model on the train set
accuracy_train = accuracy_score(y_train, y_pred_train)
precision_train = precision_score(y_train, y_pred_train)
recall_train = recall_score(y_train, y_pred_train)
f1_train = f1_score(y_train, y_pred_train)

print(f"Accuracy: {accuracy_train}")
print(f"Precision: {precision_train}")
print(f"Recall: {recall_train}")
print(f"f1: {f1_train}")

Accuracy: 0.6901399584531128
Precision: 0.6611859585508424
Recall: 0.8433811802232855
f1: 0.7412521245466174

In [266]:
# Predicting on the test set
y_pred_test = model.predict(x_test)

accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test)
recall_test = recall_score(y_test, y_pred_test)
f1_test = f1_score(y_test, y_pred_test)
print(f"Accuracy: {accuracy_test}")
print(f"Precision: {precision_test}")
print(f"Recall: {recall_test}")
print(f"f1: {f1_test}")

Accuracy: 0.6783046579941251
Precision: 0.64746772591857
Recall: 0.8400708648735706
f1: 0.7313003855590606