In [41]:
import pandas as pd

`clean-weather.csv` contains the weather/wildfire data after having being thoroughly processed and cleaned in `data-cleaning-preparation.ipnyb`.

In [42]:
df = pd.read_csv('clean-weather-2.csv')

In [43]:
df.head()

,LATITUDE,LONGITUDE,ELEVATION,STATION_NAME,PROVINCE_CODE,ID,LOCAL_DATE,LOCAL_DAY,LOCAL_MONTH,LOCAL_YEAR,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,SNOW_ON_GROUND,TOTAL_SNOW,TOTAL_PRECIPITATION,TOTAL_RAIN,hectares
0,50.9050,-126.9292,14.0,EGG ISLAND,BC,1062646.2000.3.10,2000-03-10 00:00:00,10.0,3.0,2000.0,2.0,11.3,6.7,0.0,0.0,3.5,3.5,6.0
1,59.9617,-121.3608,498.0,SAMBAA K'E,NT,220CQHR.2000.6.27,2000-06-27 00:00:00,27.0,6.0,2000.0,7.9,27.0,17.5,0.0,0.0,0.0,0.0,1000.0
2,59.9752,-121.0342,498.0,SAMBAA K'E,NT,220CQHR.2000.7.11,2000-07-11 00:00:00,11.0,7.0,2000.0,9.9,20.9,15.4,0.0,0.0,0.0,0.0,12.0
3,59.1767,-122.0190,378.3,FORT NELSON UA,BC,1192950.2001.6.13,2001-06-13 00:00:00,13.0,6.0,2001.0,8.5,26.8,17.7,0.0,0.0,0.0,0.0,5.0
4,59.4008,-120.6438,777.2,PETITOT LO,AB,3075171.2000.6.26,2000-06-26 00:00:00,26.0,6.0,2000.0,8.0,24.0,16.0,0.0,0.0,1.2,1.2,0.1

In [44]:
df.describe()

,LATITUDE,LONGITUDE,ELEVATION,LOCAL_DAY,LOCAL_MONTH,LOCAL_YEAR,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,SNOW_ON_GROUND,TOTAL_SNOW,TOTAL_PRECIPITATION,TOTAL_RAIN,hectares
count,59732.000000,59732.000000,59572.000000,59732.00000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000,59732.000000
mean,52.430932,-101.861180,498.738882,15.50437,5.835147,2009.038204,4.713177,18.190861,11.467476,2.705826,0.106384,1.673659,1.125370,248.934998
std,4.680110,20.590721,389.618273,8.80355,1.794696,6.677045,8.798398,9.858715,8.986341,12.224479,1.051774,4.796884,4.046445,5267.998994
min,40.065300,-162.480000,1.200000,1.00000,1.000000,1999.000000,-46.900000,-42.700000,-44.800000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,49.230000,-117.542833,226.125000,8.00000,5.000000,2003.000000,-0.100000,12.600000,6.500000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,51.958800,-110.581933,390.800000,15.00000,6.000000,2007.000000,6.100000,20.000000,13.400000,0.000000,0.000000,0.000000,0.000000,0.009000
75%,55.411950,-85.678991,683.300000,23.00000,7.000000,2014.000000,11.000000,25.400000,18.000000,0.000000,0.000000,0.900000,0.000000,0.200000
max,82.310400,116.188000,2926.100000,31.00000,12.000000,2024.000000,26.500000,47.900000,34.400000,322.000000,38.600000,168.000000,168.000000,577646.800000

# Modeling
It is not evident which model would best be used for our dataset, so we perform simple tests to see if basic models might be viable using a single test-train split

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error

In [46]:
x = df[['LATITUDE', 'LONGITUDE', 'MIN_TEMPERATURE', 'MAX_TEMPERATURE', 'MIN_TEMPERATURE', 'SNOW_ON_GROUND', 'TOTAL_SNOW', 'TOTAL_PRECIPITATION', 'TOTAL_RAIN', 'MIN_REL_HUMIDITY', 'MAX_REL_HUMIDITY', 'SPEED_MAX_GUST']] # Only select weather data
# x = df[['MIN_TEMPERATURE', 'MAX_TEMPERATURE', 'MIN_TEMPERATURE', 'SNOW_ON_GROUND', 'TOTAL_SNOW', 'TOTAL_PRECIPITATION', 'TOTAL_RAIN']] # Only select weather data
y = df['hectares']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

KeyError: "['MIN_REL_HUMIDITY', 'MAX_REL_HUMIDITY', 'SPEED_MAX_GUST'] not in index"

## Linear Regression model

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()
model.fit(x_train, y_train)

In [ ]:
# Predicting on the train set
y_pred = model.predict(x_test)

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

In [ ]:
y_train_pred = model.predict(x_train)

In [ ]:
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

## Decision Tree Regressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
model = DecisionTreeRegressor()
model.fit(x_train, y_train)

In [ ]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

In [ ]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

Decision Tree Regressor has overfit

## Random Forests Regressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model = RandomForestRegressor()
model.fit(x_train, y_train)

In [ ]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

In [ ]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

## Gradient Boosting Model

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
model = GradientBoostingRegressor()
model.fit(x_train, y_train)

In [47]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

MAE: 334.4183058567978
MSE: 43989679.45379763
RMSE: 6632.471594646872
R²: -0.0025468410102185146

In [ ]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

## K-Nearest Neighbors

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
model = KNeighborsRegressor()
model.fit(x_train, y_train)

In [ ]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

In [ ]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

## Support Vector Machines

In [ ]:
from sklearn.svm import SVR

In [ ]:
model = SVR()
model.fit(x_train, y_train)

In [ ]:
# Predicting on the test set
y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")

In [ ]:
# Predicting on train set
y_train_pred = model.predict(x_train)
mae = mean_absolute_error(y_train, y_train_pred)
mse = mean_squared_error(y_train, y_train_pred)
rmse = root_mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R²: {r2}")